language: c

sudo: required

addons:
    apt:
      update: true

cache:
  directories:
  - armchroot
  - .thirdparty-cache

aliases:
  - &mac-build
    os: osx
    osx_image: xcode7.3

jobs:
  fast_finish: true
  include:
  - stage: "Main Pharo builds"
    env: ARCH="linux32x86" FLAVOR="pharo.cog.spur" HEARTBEAT="threaded"
  - env: ARCH="macos32x86" FLAVOR="pharo.cog.spur"
    <<: *mac-build
  - env: ARCH="linux64x64" FLAVOR="pharo.cog.spur" HEARTBEAT="threaded"
  - env: ARCH="macos64x64" FLAVOR="pharo.cog.spur"
    <<: *mac-build

  - stage: "Other Linux builds"
    env: ARCH="linux64x64" FLAVOR="pharo.cog.spur" HEARTBEAT="itimer"
  - env: ARCH="linux32x86" FLAVOR="pharo.cog.spur" HEARTBEAT="itimer"
#  - env: ARCH="linux32x86" FLAVOR="pharo.sista.spur" HEARTBEAT="threaded"
#    compiler: clang
#  - env: ARCH="linux32x86" FLAVOR="pharo.sista.spur" HEARTBEAT="itimer" 
#    compiler: clang

#  - stage: "Other Mac builds"
#  - env: ARCH="macos64x64" FLAVOR="pharo.cog.spur.lowcode"
#    <<: *mac-build
#  - env: ARCH="macos32x86" FLAVOR="pharo.sista.spur"
#    <<: *mac-build
#  - env: ARCH="macos32x86" FLAVOR="pharo.cog.spur.lowcode"
#    <<: *mac-build

#  - stage: "Stack builds"
#    env: ARCH="linux64x64" FLAVOR="newspeak.stack.spur"
#  - env: ARCH="linux64x64" FLAVOR="squeak.stack.spur"
#  - env: ARCH="linux32x86" FLAVOR="newspeak.stack.spur"
#  - env: ARCH="linux32x86" FLAVOR="squeak.stack.spur"
#  - env: ARCH="linux32x86" FLAVOR="squeak.stack.v3"
#  - env: ARCH="macos64x64" FLAVOR="pharo.stack.spur"
#    <<: *mac-build
#  - env: ARCH="macos64x64" FLAVOR="pharo.stack.spur.lowcode"
#    <<: *mac-build
#  - env: ARCH="macos64x64" FLAVOR="squeak.stack.spur"
#    <<: *mac-build
#  - env: ARCH="macos32x86" FLAVOR="newspeak.stack.spur"
#    <<: *mac-build
#  - env: ARCH="macos64x64" FLAVOR="newspeak.stack.spur"
#    <<: *mac-build
#  - env: ARCH="macos32x86" FLAVOR="pharo.stack.spur"
#    <<: *mac-build
#  - env: ARCH="macos32x86" FLAVOR="pharo.stack.spur.lowcode"
#    <<: *mac-build
#  - env: ARCH="macos32x86" FLAVOR="squeak.stack.spur"
#    <<: *mac-build
#  - env: ARCH="macos32x86" FLAVOR="squeak.stack.v3"
#    <<: *mac-build

#  - stage: "linux32ARMv6 builds"
#    env: ARCH="linux32ARMv6" FLAVOR="newspeak.cog.spur" CHROOT="schroot -p -c rpi
#      -- bash -c "
#    dist: trusty
#    group: edge
#  - env: ARCH="linux32ARMv6" FLAVOR="newspeak.stack.spur" CHROOT="schroot -p -c rpi
#      -- bash -c "
#    dist: trusty
#    group: edge
#  - env: ARCH="linux32ARMv6" FLAVOR="squeak.cog.spur" CHROOT="schroot -p -c rpi --
#      bash -c "
#    dist: trusty
#    group: edge
#  - env: ARCH="linux32ARMv6" FLAVOR="pharo.cog.spur" CHROOT="schroot -p -c rpi --
#      bash -c "
#    dist: trusty
#    group: edge
#  - env: ARCH="linux32ARMv6" FLAVOR="squeak.stack.spur" CHROOT="schroot -p -c rpi
#      -- bash -c "
#    dist: trusty
#    group: edge
#  - env: ARCH="linux32ARMv6" FLAVOR="squeak.stack.v3" CHROOT="schroot -p -c rpi --
#      bash -c "
#    dist: trusty
#    group: edge
#  allow_failures:
#  - env: FLAVOR="squeak.sista.spur"
#  - env: FLAVOR="pharo.sista.spur"
#  - env: FLAVOR="squeak.cog.spur.lowcode"
#  - env: FLAVOR="pharo.cog.spur.lowcode"

install: ./scripts/ci/travis_install.sh

before_script: $CHROOT ./scripts/ci/travis_build.sh

script: ./scripts/ci/travis_test.sh

after_success: (cd deploy && ./filter-exec.sh pack-vm.sh)

deploy:
  provider: releases
  api_key:
    secure: Wcol6atwCtywPaCq1xRjfVIxt+HrYq/vrxHgDdr4WBm+s99nREdxiaIpnPb3S2Qu+H3S3dLmFJ/1pqfltnRn71eOaXktAJkl/iQFoA47YEXdU/tRi2xDZHRSsc61MYaPlap1A0byfOhq8Lj9lx2ojzL7DevJ0Q9JDbwWVy2QuDh+54fKymHo9Q9ta43Yxk8yltXU8f0lhwOMNMORRISp9O10CetlgFclSkX7/FJvLQ7YqWUNngA1BWWR+7sgAxwQDalIPmVJN6q5dDOSoutXEqe0TjnKHAf0HIGbLpMsDB1E8JoUasHfoQvRsDSO/FeUFR+XuNlMmdyAsj/XsrvhZyKFhIssJ6X4RZmW1Ks35WesWMIPGbpEKRJjVe5Ale1NDQJfwQqj/WclfIxgucf7bUAHObCWl8GOVD493inatsHSWsjnOL0dDoumtxNDsulZyJeEPBYtItD1ThcwWpKsbTGEPlrpyvfXZscL+IBIMSKzrfprK/pUpw/Ft/TH7L397KFGE8EnzueCPMWGg+8260gHhnU7+KJvV3htKYNIWALr3pvmsf/D3QjeGUhdvAafEvNMlCKEEdO12twtNEh5VwQnGLpltxdShHwsr/Ocd/aNz9wLX2m1+u/CKriwpyqo5vZ6YrOtujqJSTCsgCpXOAVBSNdPKE6YA3iAR5bQONw=
  file: "./products/*.{dmg,gz,zip}"
  file_glob: true
  skip_cleanup: true
  on:
    repo: pharo-project/opensmalltalk-vm
    tags: true